### PR TITLE
Bugfix: Setup error handling for when file designated in etIgnore is not present

### LINKED ISSUE #17: `et submit` crashes if `.etignore` file/path doesn't exist
**To Reproduce**
1. `et get launch-sc-react-quiz-express-hooks`. Ensure that there is no `/react/coverage` directory and that the `.etignore` file contains
    ```
    # Files to ignore when uploading to Launch
    launch-sc-react-quiz-express-hooks.md
    react/coverage
    ```
2. Run `et submit`
3. See error

**Expected behavior**
Submission should be successful despite non-existence of `react/coverage`

**Screenshots**
```
~/LaunchAcademy/challenges/launch-sc-react-quiz-express-hooks$ et submit

(node:14619) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/home/jsim0809/LaunchAcademys/launch-sc-react-quiz-express-hooks/react/coverage'

    at Object.statSync (fs.js:1035:3)
    at /home/jsim0809/.nvm/versions/node/v14.0.0/lib/node_modules/extraterrestrial/src/submission/SubmissionFileBlacklist.j
    at Array.reduce (<anonymous>)
    at SubmissionFileBlacklist._processIgnoreFileList 
    at SubmissionFileBlacklist.get blacklistGlobs [as blacklistGlobs] 
    at FileList.get blacklistGlobs [as blacklistGlobs] 
    at FileList.files
    at Archive.getFileList 
    at Archive.hasFilesToSubmit 
    at LessonSubmission.submit 

~/LaunchAcademy/challenges/launch-sc-react-quiz-express-hooks$ ls
launch-sc-react-quiz-express-hooks.md  package.json  questions.json  src                yarn.lock
node_modules                           public        server          webpack.config.js
```

**Environment:**
 - OS: Windows, Mac

### PR DESCRIPTION
**Pull request by nwalberts**
- Added try...catch block for when `ENOENT: no such file or directory` error occurs during processing of blacklisted file paths

@dpickett FYI: After looking at it multiple ways, **I couldn't see the value in a test:**
- the expected final result stays exactly the same regardless of the test fixture
- couldn't see the value in testing that an error is not thrown, unless I made a more contrived fixture that had an erroneous file path, and one that didn't. I DID add an erroneous file path to the fixture that is already in use however, so it is controlling for that functionality 
- for all other errors, I didnt see value in testing, because then I would have to edit the code to force an error to be thrown when running fs.statSync()

Let me know if there is feedback to better test though. 

Doesn't look like there is a way to test a branch of et-node, so I will click test after the merge (unless there is a better workflow for deployment)

### CODE REVIEW

File: src/submission/SubmissionFileBlacklist.js [hunk 1]
```diff
@@ -34,11 +34,20 @@ class SubmissionFileBlacklist {
...
+        try {
+          const fileOrDir = fs.statSync(path.join(this.directory, fileLine))
+          // console.log("File exists.");
+
+          if (fileOrDir.isDirectory()) {
+            fileLine = this._formatDirectoryGlob(fileLine)
+          }
+          return [...globs, fileLine]
+        }
+        catch (error) {
```
Comment (dpickett) [inline src/submission/SubmissionFileBlacklist.js:41]: we should check specifically for the `ENOENT` error and throw otherwise.

File: src/submission/SubmissionFileBlacklist.js [hunk 2]
```diff
@@ -34,11 +34,20 @@ class SubmissionFileBlacklist {
       if (fileLine.startsWith("#") || fileLine.length === 0) {
         return [...globs]
       } else {
-        const fileOrDir = fs.statSync(path.join(this.directory, fileLine))
-        if (fileOrDir.isDirectory()) {
-          fileLine = this._formatDirectoryGlob(fileLine)
+        try {
+          const fileOrDir = fs.statSync(path.join(this.directory, fileLine))
+          // console.log("File exists.");
```
Comment (dpickett) [inline src/submission/SubmissionFileBlacklist.js]: let's remove this line

File: src/submission/SubmissionFileBlacklist.js (hunk 1 above)
Comment (dpickett) [reply src/submission/SubmissionFileBlacklist.js:41]: the `try` should really only be around the `statSync` call because that is where we anticipate the error to occur

**Review by dpickett — CHANGES_REQUESTED** [review]

**Review by dpickett — APPROVED** [review]
